- name: configure LAMP stack
  hosts: webappphp
  become: yes
  become_user: root
  tasks:
    - name: Installinga Apache server
      yum: name=httpd state=latest

    - name: Start Apache Server Services
      service: name=httpd state=started
    
    - name: Installing MariaDB Server
      yum:
       name:
       - mariadb-server
       - mariadb-devel
       - mariadb-connectot-odbc
       - mariadb-server-utils
       - python3-PyMySQL
       - php
       state: latest

    - name: start MariaDB Server Service
      service: name=mariadb state=started

    - name: Update MariaDB Server root password
      mysql_user:
        name: root
        host: SQLserver192.168.104.16
        password: mysql@123
        login_user: root
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"

    - name: Create a new database called zelar
      mysql_db: name=zelar state=present login_user=root login_password=mysql@123

    - name: Copy SQL file
      copy: src-=/source/servers.sql dest=/tmp/servers.sql

    - name: Create Table called whole data
      shell: mysql -u root -pmysql zelar < /tmp/servers.sql

    - name: Copy PHP files
      copy: src=/source/connection.php dest=/var/www/html/

    - name: copy index.php file
      copy: src=/source/index.php dest=/var/www/html/

    - name: Restart web services
      service: name=httpd state=restartde
